2021-03-22 23:10:04,287 INFO    MainThread:2995 [internal.py:wandb_internal():88] W&B internal server running at pid: 2995, started at: 2021-03-22 23:10:04.287605
2021-03-22 23:10:04,288 DEBUG   HandlerThread:2995 [handler.py:handle_request():101] handle_request: check_version
2021-03-22 23:10:04,288 INFO    WriterThread:2995 [datastore.py:open_for_write():77] open: /Users/parimalkumar/Documents/Snehal/coursesIITMsem2/cs6910-DL/CS6910-Asignment-1/assignment-1-v-2/wandb_integration/wandb/run-20210322_231003-s0jrit6o/run-s0jrit6o.wandb
2021-03-22 23:10:04,289 DEBUG   SenderThread:2995 [sender.py:send():161] send: header
2021-03-22 23:10:04,289 DEBUG   SenderThread:2995 [sender.py:send():161] send: request
2021-03-22 23:10:04,292 DEBUG   SenderThread:2995 [sender.py:send_request():170] send_request: check_version
2021-03-22 23:10:04,480 DEBUG   SenderThread:2995 [sender.py:send():161] send: run
2021-03-22 23:10:04,881 INFO    SenderThread:2995 [sender.py:_start_run_threads():635] run started: s0jrit6o with start time 1616434803
2021-03-22 23:10:04,882 DEBUG   SenderThread:2995 [sender.py:send():161] send: summary
2021-03-22 23:10:04,882 INFO    SenderThread:2995 [sender.py:_save_file():769] saving file wandb-summary.json with policy end
2021-03-22 23:10:04,887 DEBUG   HandlerThread:2995 [handler.py:handle_request():101] handle_request: run_start
2021-03-22 23:10:05,838 DEBUG   HandlerThread:2995 [meta.py:__init__():34] meta init
2021-03-22 23:10:05,838 DEBUG   HandlerThread:2995 [meta.py:__init__():48] meta init done
2021-03-22 23:10:05,839 DEBUG   HandlerThread:2995 [meta.py:probe():190] probe
2021-03-22 23:10:05,840 DEBUG   HandlerThread:2995 [meta.py:_setup_git():180] setup git
2021-03-22 23:10:05,858 DEBUG   HandlerThread:2995 [meta.py:_setup_git():187] setup git done
2021-03-22 23:10:05,859 DEBUG   HandlerThread:2995 [meta.py:_save_pip():52] save pip
2021-03-22 23:10:05,859 DEBUG   HandlerThread:2995 [meta.py:_save_pip():66] save pip done
2021-03-22 23:10:05,859 DEBUG   HandlerThread:2995 [meta.py:probe():231] probe done
2021-03-22 23:10:05,861 DEBUG   SenderThread:2995 [sender.py:send():161] send: files
2021-03-22 23:10:05,862 INFO    SenderThread:2995 [sender.py:_save_file():769] saving file wandb-metadata.json with policy now
2021-03-22 23:10:05,864 DEBUG   HandlerThread:2995 [handler.py:handle_request():101] handle_request: status
2021-03-22 23:10:05,864 DEBUG   SenderThread:2995 [sender.py:send():161] send: request
2021-03-22 23:10:05,864 DEBUG   SenderThread:2995 [sender.py:send_request():170] send_request: status
2021-03-22 23:10:07,306 DEBUG   SenderThread:2995 [sender.py:send():161] send: telemetry
2021-03-22 23:10:21,179 DEBUG   HandlerThread:2995 [handler.py:handle_request():101] handle_request: status
2021-03-22 23:10:21,180 DEBUG   SenderThread:2995 [sender.py:send():161] send: request
2021-03-22 23:10:21,180 DEBUG   SenderThread:2995 [sender.py:send_request():170] send_request: status
2021-03-22 23:10:36,567 DEBUG   HandlerThread:2995 [handler.py:handle_request():101] handle_request: status
2021-03-22 23:10:36,567 DEBUG   SenderThread:2995 [sender.py:send():161] send: request
2021-03-22 23:10:36,567 DEBUG   SenderThread:2995 [sender.py:send_request():170] send_request: status
2021-03-22 23:10:51,926 DEBUG   HandlerThread:2995 [handler.py:handle_request():101] handle_request: status
2021-03-22 23:10:51,927 DEBUG   SenderThread:2995 [sender.py:send():161] send: request
2021-03-22 23:10:51,927 DEBUG   SenderThread:2995 [sender.py:send_request():170] send_request: status
2021-03-22 23:11:00,115 DEBUG   SenderThread:2995 [sender.py:send():161] send: stats
2021-03-22 23:11:07,287 DEBUG   HandlerThread:2995 [handler.py:handle_request():101] handle_request: status
2021-03-22 23:11:07,288 DEBUG   SenderThread:2995 [sender.py:send():161] send: request
2021-03-22 23:11:07,288 DEBUG   SenderThread:2995 [sender.py:send_request():170] send_request: status
2021-03-22 23:11:22,647 DEBUG   HandlerThread:2995 [handler.py:handle_request():101] handle_request: status
2021-03-22 23:11:22,647 DEBUG   SenderThread:2995 [sender.py:send():161] send: request
2021-03-22 23:11:22,647 DEBUG   SenderThread:2995 [sender.py:send_request():170] send_request: status
2021-03-22 23:11:37,968 DEBUG   HandlerThread:2995 [handler.py:handle_request():101] handle_request: status
2021-03-22 23:11:37,969 DEBUG   SenderThread:2995 [sender.py:send():161] send: request
2021-03-22 23:11:37,969 DEBUG   SenderThread:2995 [sender.py:send_request():170] send_request: status
2021-03-22 23:11:53,363 DEBUG   HandlerThread:2995 [handler.py:handle_request():101] handle_request: status
2021-03-22 23:11:53,363 DEBUG   SenderThread:2995 [sender.py:send():161] send: request
2021-03-22 23:11:53,363 DEBUG   SenderThread:2995 [sender.py:send_request():170] send_request: status
2021-03-22 23:11:56,464 DEBUG   SenderThread:2995 [sender.py:send():161] send: stats
2021-03-22 23:12:08,726 DEBUG   HandlerThread:2995 [handler.py:handle_request():101] handle_request: status
2021-03-22 23:12:08,727 DEBUG   SenderThread:2995 [sender.py:send():161] send: request
2021-03-22 23:12:08,727 DEBUG   SenderThread:2995 [sender.py:send_request():170] send_request: status
2021-03-22 23:12:24,046 DEBUG   HandlerThread:2995 [handler.py:handle_request():101] handle_request: status
2021-03-22 23:12:24,047 DEBUG   SenderThread:2995 [sender.py:send():161] send: request
2021-03-22 23:12:24,047 DEBUG   SenderThread:2995 [sender.py:send_request():170] send_request: status
2021-03-22 23:12:24,893 DEBUG   SenderThread:2995 [sender.py:send():161] send: history
2021-03-22 23:12:24,893 DEBUG   SenderThread:2995 [sender.py:send():161] send: summary
2021-03-22 23:12:24,894 INFO    SenderThread:2995 [sender.py:_save_file():769] saving file wandb-summary.json with policy end
2021-03-22 23:12:24,895 DEBUG   HandlerThread:2995 [handler.py:handle_request():101] handle_request: poll_exit
2021-03-22 23:12:24,895 DEBUG   SenderThread:2995 [sender.py:send():161] send: telemetry
2021-03-22 23:12:25,222 ERROR   SenderThread:2995 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-03-22 23:12:25,222 ERROR   SenderThread:2995 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '254298-s0jrit6o' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-03-22 23:12:26,702 ERROR   SenderThread:2995 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-03-22 23:12:26,702 ERROR   SenderThread:2995 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '254298-s0jrit6o' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-03-22 23:12:29,160 ERROR   SenderThread:2995 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-03-22 23:12:29,160 ERROR   SenderThread:2995 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '254298-s0jrit6o' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-03-22 23:12:29,161 ERROR   SenderThread:2995 [retry.py:__call__():111] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/parimalkumar/DL/lib/python3.8/site-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/parimalkumar/DL/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 129, in execute
    six.reraise(*sys.exc_info())
  File "/Users/parimalkumar/DL/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/Users/parimalkumar/DL/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 123, in execute
    return self.client.execute(*args, **kwargs)
  File "/Users/parimalkumar/DL/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/parimalkumar/DL/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/parimalkumar/DL/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/Users/parimalkumar/DL/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2021-03-22 23:12:33,970 ERROR   SenderThread:2995 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-03-22 23:12:33,971 ERROR   SenderThread:2995 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '254298-s0jrit6o' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-03-22 23:12:42,979 ERROR   SenderThread:2995 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-03-22 23:12:42,979 ERROR   SenderThread:2995 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '254298-s0jrit6o' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-03-22 23:13:02,128 ERROR   SenderThread:2995 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-03-22 23:13:02,128 ERROR   SenderThread:2995 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '254298-s0jrit6o' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-03-22 23:13:38,706 ERROR   SenderThread:2995 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-03-22 23:13:38,707 ERROR   SenderThread:2995 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '254298-s0jrit6o' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-03-22 23:14:48,525 ERROR   SenderThread:2995 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-03-22 23:14:48,527 ERROR   SenderThread:2995 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '254298-s0jrit6o' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-03-22 23:17:14,194 ERROR   SenderThread:2995 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-03-22 23:17:14,195 ERROR   SenderThread:2995 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '254298-s0jrit6o' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-03-22 23:22:19,807 ERROR   SenderThread:2995 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-03-22 23:22:19,807 ERROR   SenderThread:2995 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '254298-s0jrit6o' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-03-22 23:28:28,247 ERROR   SenderThread:2995 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-03-22 23:28:28,247 ERROR   SenderThread:2995 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '254298-s0jrit6o' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-03-22 23:34:11,009 ERROR   SenderThread:2995 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-03-22 23:34:11,010 ERROR   SenderThread:2995 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '254298-s0jrit6o' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-03-22 23:39:47,068 ERROR   SenderThread:2995 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-03-22 23:39:47,070 ERROR   SenderThread:2995 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '254298-s0jrit6o' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-03-22 23:45:48,899 ERROR   SenderThread:2995 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-03-22 23:45:48,901 ERROR   SenderThread:2995 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '254298-s0jrit6o' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-03-22 23:50:50,629 ERROR   SenderThread:2995 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-03-22 23:50:50,631 ERROR   SenderThread:2995 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '254298-s0jrit6o' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-03-22 23:56:02,646 ERROR   SenderThread:2995 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-03-22 23:56:02,647 ERROR   SenderThread:2995 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '254298-s0jrit6o' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-03-23 00:02:02,996 ERROR   SenderThread:2995 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-03-23 00:02:02,998 ERROR   SenderThread:2995 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '254298-s0jrit6o' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-03-23 00:07:08,971 ERROR   SenderThread:2995 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-03-23 00:07:08,971 ERROR   SenderThread:2995 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '254298-s0jrit6o' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-03-23 00:13:09,477 WARNING MainThread:2995 [internal.py:is_dead():343] Internal process exiting, parent pid 2988 disappeared
2021-03-23 00:13:09,478 ERROR   MainThread:2995 [internal.py:wandb_internal():142] Internal process shutdown.
2021-03-23 00:13:09,899 INFO    WriterThread:2995 [datastore.py:close():258] close: /Users/parimalkumar/Documents/Snehal/coursesIITMsem2/cs6910-DL/CS6910-Asignment-1/assignment-1-v-2/wandb_integration/wandb/run-20210322_231003-s0jrit6o/run-s0jrit6o.wandb
2021-03-23 00:13:09,923 INFO    HandlerThread:2995 [handler.py:finish():535] shutting down handler
2021-03-23 00:13:10,624 ERROR   SenderThread:2995 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-03-23 00:13:10,624 ERROR   SenderThread:2995 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '254298-s0jrit6o' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
